version: '3.8'

services:
  # Override backend service for development
  backend:
    build:
      target: development
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
    command: npm run dev
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  # Expose PostgreSQL port for external access
  postgres:
    ports:
      - "5432:5432"

  # Expose Redis port for external access
  redis:
    ports:
      - "6379:6379"

  # Expose pgAdmin port for database management
  pgadmin:
    ports:
      - "5050:80"
